// published are the addresses the site has handed out: the consent screen of
// the sign-in points at two of them, and a listing points at the apex. A build
// that dropped one would break a link somebody else holds, and nothing on the
// site need still link to it for the link rule to notice. An anchor linked from
// outside its page is held the same way, written after its page's address, and
// its page must still hold an element with that id. The list is written by
// hand, address by address, and never worked out from the site's texts, so that
// a page going missing from them cannot take its address off the list.
export const published: readonly string[] = [
	"/",
	"/en/",
	"/en/privacy/",
	"/en/terms/",
	"/en/topics/",
	"/en/topics/#logic",
	"/en/topics/#counting",
	"/en/topics/#time",
	"/en/topics/#numbers",
	"/en/topics/ordering/",
	"/en/topics/ordering/#traps",
	"/en/topics/ordering/#home",
	"/en/topics/knights-and-liars/",
	"/en/topics/knights-and-liars/#traps",
	"/en/topics/knights-and-liars/#home",
	"/en/topics/enumeration/",
	"/en/topics/enumeration/#traps",
	"/en/topics/enumeration/#home",
	"/en/topics/gaps-and-boundaries/",
	"/en/topics/gaps-and-boundaries/#traps",
	"/en/topics/gaps-and-boundaries/#home",
	"/en/topics/clocks/",
	"/en/topics/clocks/#traps",
	"/en/topics/clocks/#home",
	"/en/topics/calendar-and-age/",
	"/en/topics/calendar-and-age/#traps",
	"/en/topics/calendar-and-age/#home",
	"/en/topics/pigeonhole-principle/",
	"/en/topics/pigeonhole-principle/#traps",
	"/en/topics/pigeonhole-principle/#home",
	"/en/topics/parity-and-alternation/",
	"/en/topics/parity-and-alternation/#traps",
	"/en/topics/parity-and-alternation/#home",
	"/en/topics/overlapping-groups/",
	"/en/topics/overlapping-groups/#traps",
	"/en/topics/overlapping-groups/#home",
	"/en/why/",
	"/ru/",
	"/ru/privacy/",
	"/ru/terms/",
	"/ru/topics/",
	"/ru/topics/#logic",
	"/ru/topics/#counting",
	"/ru/topics/#time",
	"/ru/topics/#numbers",
	"/ru/topics/ordering/",
	"/ru/topics/ordering/#traps",
	"/ru/topics/ordering/#home",
	"/ru/topics/knights-and-liars/",
	"/ru/topics/knights-and-liars/#traps",
	"/ru/topics/knights-and-liars/#home",
	"/ru/topics/enumeration/",
	"/ru/topics/enumeration/#traps",
	"/ru/topics/enumeration/#home",
	"/ru/topics/gaps-and-boundaries/",
	"/ru/topics/gaps-and-boundaries/#traps",
	"/ru/topics/gaps-and-boundaries/#home",
	"/ru/topics/clocks/",
	"/ru/topics/clocks/#traps",
	"/ru/topics/clocks/#home",
	"/ru/topics/calendar-and-age/",
	"/ru/topics/calendar-and-age/#traps",
	"/ru/topics/calendar-and-age/#home",
	"/ru/topics/pigeonhole-principle/",
	"/ru/topics/pigeonhole-principle/#traps",
	"/ru/topics/pigeonhole-principle/#home",
	"/ru/topics/parity-and-alternation/",
	"/ru/topics/parity-and-alternation/#traps",
	"/ru/topics/parity-and-alternation/#home",
	"/ru/topics/overlapping-groups/",
	"/ru/topics/overlapping-groups/#traps",
	"/ru/topics/overlapping-groups/#home",
	"/ru/why/",
];
